import { PresetTemplate } from '../types';

export const PRESET_TEMPLATES: PresetTemplate[] = [
  {
    id: 'classic',
    nameAr: 'أسود كلاسيكي',
    nameEn: 'Classic Black',
    fgColor: '#000000',
    bgColor: '#ffffff',
    dotStyle: 'square',
    eyeStyle: 'square',
  },
  {
    id: 'emerald',
    nameAr: 'زمردي عصري',
    nameEn: 'Modern Emerald',
    fgColor: '#065f46',
    bgColor: '#f0fdf4',
    dotStyle: 'rounded',
    eyeStyle: 'rounded',
  },
  {
    id: 'indigo',
    nameAr: 'أزرق ملكي',
    nameEn: 'Royal Indigo',
    fgColor: '#312e81',
    bgColor: '#eef2ff',
    dotStyle: 'dots',
    eyeStyle: 'circle',
  },
  {
    id: 'sunset',
    nameAr: 'ذهب الغروب',
    nameEn: 'Sunset Gold',
    fgColor: '#78350f',
    bgColor: '#fffbeb',
    dotStyle: 'rounded',
    eyeStyle: 'rounded',
  },
  {
    id: 'rose',
    nameAr: 'وردي فاخر',
    nameEn: 'Luxury Rose',
    fgColor: '#831843',
    bgColor: '#fdf2f8',
    dotStyle: 'dots',
    eyeStyle: 'circle',
  },
  {
    id: 'dark',
    nameAr: 'داكن احترافي',
    nameEn: 'Pro Dark',
    fgColor: '#f8fafc',
    bgColor: '#0f172a',
    dotStyle: 'rounded',
    eyeStyle: 'rounded',
  },
  {
    id: 'cyberpunk',
    nameAr: 'سايبر نيون',
    nameEn: 'Cyber Neon',
    fgColor: '#06b6d4',
    bgColor: '#090d16',
    dotStyle: 'dots',
    eyeStyle: 'circle',
  },
];
